# Generated by Django 5.1.6 on 2025-03-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
